-- Drop existing tables if they exist
-- DROP TABLE IF EXISTS rentals;
-- DROP TABLE IF EXISTS tools;

-- Create tools table
CREATE TABLE IF NOT EXISTS tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    available_qty INTEGER NOT NULL DEFAULT 0,
    rate_per_day NUMERIC(10, 2) NOT NULL DEFAULT 0.00
);

-- Create rentals table
CREATE TABLE IF NOT EXISTS rentals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id UUID NOT NULL,
    customer_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    tool_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    rent_date DATE NOT NULL,
    return_date DATE NOT NULL,
    actual_return_date DATE,
    days INTEGER,
    amount NUMERIC(10, 2),
    returned BOOLEAN NOT NULL DEFAULT FALSE,
    paid BOOLEAN NOT NULL DEFAULT TRUE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_tools_name ON tools(name);
CREATE INDEX IF NOT EXISTS idx_rentals_group_id ON rentals(group_id);
CREATE INDEX IF NOT EXISTS idx_rentals_customer_name ON rentals(customer_name);
CREATE INDEX IF NOT EXISTS idx_rentals_phone ON rentals(phone);

-- RPC 1: Rent multiple tools atomically
CREATE OR REPLACE FUNCTION rent_tools(
    p_customer_name TEXT,
    p_phone TEXT,
    p_rent_date DATE,
    p_return_date DATE,
    p_items JSONB -- Array of {name: string, qty: number}
)
RETURNS UUID AS $$
DECLARE
    v_group_id UUID;
    v_item JSONB;
    v_tool_name TEXT;
    v_qty INTEGER;
    v_available_qty INTEGER;
BEGIN
    -- Generate group_id
    v_group_id := gen_random_uuid();
    
    -- Loop over items and check stock
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_tool_name := (v_item->>'name');
        v_qty := (v_item->>'qty')::INTEGER;
        
        -- Validate quantity
        IF v_qty <= 0 THEN
            RAISE EXCEPTION 'Quantity for % must be greater than zero', v_tool_name;
        END IF;
        
        -- Lock row and get available quantity
        SELECT available_qty INTO v_available_qty
        FROM tools
        WHERE name = v_tool_name
        FOR UPDATE;
        
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Tool % not found', v_tool_name;
        END IF;
        
        IF v_available_qty < v_qty THEN
            RAISE EXCEPTION 'Not enough stock for % (Available: %, Requested: %)', v_tool_name, v_available_qty, v_qty;
        END IF;
        
        -- Update tool stock
        UPDATE tools
        SET available_qty = available_qty - v_qty
        WHERE name = v_tool_name;
        
        -- Insert rental record
        INSERT INTO rentals (
            group_id, customer_name, phone, tool_name, quantity, rent_date, return_date, returned, paid
        )
        VALUES (
            v_group_id, TRIM(p_customer_name), TRIM(p_phone), v_tool_name, v_qty, p_rent_date, p_return_date, FALSE, TRUE
        );
    END LOOP;
    
    RETURN v_group_id;
END;
$$ LANGUAGE plpgsql;

-- RPC 2: Return a rental group atomically
DROP FUNCTION IF EXISTS return_rental(UUID, DATE, BOOLEAN);
CREATE OR REPLACE FUNCTION return_rental(
    p_group_id UUID,
    p_actual_return_date DATE,
    p_paid BOOLEAN
)
RETURNS TABLE (
    out_group_id UUID,
    out_customer_name TEXT,
    out_phone TEXT,
    out_rent_date DATE,
    out_return_date DATE,
    out_actual_return_date DATE,
    out_days INTEGER,
    out_amount NUMERIC(10, 2),
    out_returned BOOLEAN
) AS $$
DECLARE
    v_rental RECORD;
    v_rate NUMERIC(10, 2);
    v_days INTEGER;
    v_amount NUMERIC(10, 2);
BEGIN
    -- Check if rental group exists and is active
    PERFORM 1 FROM rentals WHERE group_id = p_group_id LIMIT 1;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Rental group not found';
    END IF;
    
    IF EXISTS (SELECT 1 FROM rentals WHERE group_id = p_group_id AND returned = TRUE) THEN
        RAISE EXCEPTION 'Rental group is already returned';
    END IF;
    
    -- Process each tool in the rental group
    FOR v_rental IN SELECT * FROM rentals WHERE group_id = p_group_id
    LOOP
        -- Get tool rate
        SELECT rate_per_day INTO v_rate FROM tools WHERE name = v_rental.tool_name;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Rate per day not found for tool %', v_rental.tool_name;
        END IF;
        
        -- Calculate rental days and amount
        v_days := p_actual_return_date - v_rental.rent_date;
        IF v_days < 1 THEN
            v_days := 1;
        END IF;
        
        v_amount := v_days * v_rental.quantity * v_rate;
        
        -- Update rental record
        UPDATE rentals
        SET actual_return_date = p_actual_return_date,
            days = v_days,
            amount = v_amount,
            returned = TRUE,
            paid = p_paid
        WHERE id = v_rental.id;
        
        -- Restore tool stock
        UPDATE tools
        SET available_qty = available_qty + v_rental.quantity
        WHERE name = v_rental.tool_name;
    END LOOP;
    
    -- Return summary row
    RETURN QUERY
    SELECT 
        r.group_id as out_group_id,
        r.customer_name as out_customer_name,
        r.phone as out_phone,
        MIN(r.rent_date) as out_rent_date,
        MIN(r.return_date) as out_return_date,
        MIN(r.actual_return_date) as out_actual_return_date,
        MIN(r.days) as out_days,
        SUM(r.amount) as out_amount,
        TRUE as out_returned
    FROM rentals r
    WHERE r.group_id = p_group_id
    GROUP BY r.group_id, r.customer_name, r.phone;
END;
$$ LANGUAGE plpgsql;

-- RPC 3: Undo a returned rental group
CREATE OR REPLACE FUNCTION undo_return_rental(
    p_group_id UUID
)
RETURNS VOID AS $$
DECLARE
    v_rental RECORD;
    v_available_qty INTEGER;
BEGIN
    -- Check if rental group exists and is returned
    PERFORM 1 FROM rentals WHERE group_id = p_group_id LIMIT 1;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Rental group not found';
    END IF;
    
    IF EXISTS (SELECT 1 FROM rentals WHERE group_id = p_group_id AND returned = FALSE) THEN
        RAISE EXCEPTION 'Rental group is active and cannot be undone';
    END IF;
    
    -- Check tool stock availability first to revert stock decrement
    FOR v_rental IN SELECT * FROM rentals WHERE group_id = p_group_id
    LOOP
        SELECT available_qty INTO v_available_qty FROM tools WHERE name = v_rental.tool_name FOR UPDATE;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Tool % not found', v_rental.tool_name;
        END IF;
        
        IF v_available_qty < v_rental.quantity THEN
            RAISE EXCEPTION 'Cannot undo: Not enough stock to re-rent % (Available: %, Required: %)', v_rental.tool_name, v_available_qty, v_rental.quantity;
        END IF;
    END LOOP;
    
    -- Decrement stock and reset fields
    FOR v_rental IN SELECT * FROM rentals WHERE group_id = p_group_id
    LOOP
        UPDATE tools
        SET available_qty = available_qty - v_rental.quantity
        WHERE name = v_rental.tool_name;
        
        UPDATE rentals
        SET actual_return_date = NULL,
            days = NULL,
            amount = NULL,
            returned = FALSE,
            paid = TRUE -- Resets to true since it goes back to active
        WHERE id = v_rental.id;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- RPC 4: Update return date of a bill
CREATE OR REPLACE FUNCTION update_return_date(
    p_group_id UUID,
    p_actual_return_date DATE
)
RETURNS VOID AS $$
DECLARE
    v_rental RECORD;
    v_rate NUMERIC(10, 2);
    v_days INTEGER;
    v_amount NUMERIC(10, 2);
BEGIN
    PERFORM 1 FROM rentals WHERE group_id = p_group_id LIMIT 1;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Rental group not found';
    END IF;
    
    IF EXISTS (SELECT 1 FROM rentals WHERE group_id = p_group_id AND returned = FALSE) THEN
        RAISE EXCEPTION 'Rental group is active. Update return date is only for returned bills';
    END IF;
    
    FOR v_rental IN SELECT * FROM rentals WHERE group_id = p_group_id
    LOOP
        SELECT rate_per_day INTO v_rate FROM tools WHERE name = v_rental.tool_name;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Rate per day not found for tool %', v_rental.tool_name;
        END IF;
        
        v_days := p_actual_return_date - v_rental.rent_date;
        IF v_days < 1 THEN
            v_days := 1;
        END IF;
        
        v_amount := v_days * v_rental.quantity * v_rate;
        
        UPDATE rentals
        SET actual_return_date = p_actual_return_date,
            days = v_days,
            amount = v_amount
        WHERE id = v_rental.id;
END;
$$ LANGUAGE plpgsql;

-- RPC 5: Edit active rental details and quantities atomically
CREATE OR REPLACE FUNCTION edit_active_rental(
    p_group_id UUID,
    p_customer_name TEXT,
    p_phone TEXT,
    p_rent_date DATE,
    p_return_date DATE,
    p_items JSONB -- Array of {name: string, qty: number}
)
RETURNS VOID AS $$
DECLARE
    v_rental RECORD;
    v_item JSONB;
    v_tool_name TEXT;
    v_qty INTEGER;
    v_available_qty INTEGER;
BEGIN
    -- 1. Check if group exists and is active
    IF EXISTS (SELECT 1 FROM rentals WHERE group_id = p_group_id AND returned = TRUE) THEN
        RAISE EXCEPTION 'Cannot edit: Rental group is already returned';
    END IF;

    -- Validate items list
    IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
        RAISE EXCEPTION 'No tools selected for rental';
    END IF;

    -- 2. Restore stock for all current items in this rental group
    FOR v_rental IN SELECT * FROM rentals WHERE group_id = p_group_id
    LOOP
        UPDATE tools
        SET available_qty = available_qty + v_rental.quantity
        WHERE name = v_rental.tool_name;
    END LOOP;

    -- 3. Delete old rental records for this group
    DELETE FROM rentals WHERE group_id = p_group_id;

    -- 4. Insert new items and adjust stock
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_tool_name := (v_item->>'name');
        v_qty := (v_item->>'qty')::INTEGER;

        IF v_qty <= 0 THEN
            RAISE EXCEPTION 'Quantity for % must be greater than zero', v_tool_name;
        END IF;

        -- Lock and check available qty
        SELECT available_qty INTO v_available_qty
        FROM tools
        WHERE name = v_tool_name
        FOR UPDATE;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Tool % not found', v_tool_name;
        END IF;

        IF v_available_qty < v_qty THEN
            RAISE EXCEPTION 'Not enough stock for % (Available: %, Requested: %)', v_tool_name, v_available_qty, v_qty;
        END IF;

        -- Update stock
        UPDATE tools
        SET available_qty = available_qty - v_qty
        WHERE name = v_tool_name;

        -- Insert new rental record
        INSERT INTO rentals (
            group_id, customer_name, phone, tool_name, quantity, rent_date, return_date, returned, paid
        )
        VALUES (
            p_group_id, TRIM(p_customer_name), TRIM(p_phone), v_tool_name, v_qty, p_rent_date, p_return_date, FALSE, TRUE
        );
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- =========================================================================
-- SECURITY & ROW LEVEL SECURITY (RLS) POLICIES (Optional but Recommended)
-- =========================================================================
-- Supabase uses a client-side architecture where the Anon Key is public by design.
-- To protect your data, you should enable RLS on your tables and configure policies.
-- Run these commands in your SQL Editor to secure your database tables:

-- 1. Enable RLS on both tables
-- ALTER TABLE tools ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE rentals ENABLE ROW LEVEL SECURITY;

-- 2. Define policies for tools:
-- POLICY A: Allow anyone to read tools (needed for checkouts/dropdowns)
-- CREATE POLICY "Allow read access to anyone" ON tools FOR SELECT USING (true);
-- POLICY B: Restrict write/edit/delete actions to authenticated users only (protects inventory write-access)
-- CREATE POLICY "Allow write/edit access for authenticated users" ON tools 
--     FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 3. Define policies for rentals:
-- If this app is only accessed by yourself/authenticated operators:
-- CREATE POLICY "Allow full access for authenticated users" ON rentals 
--     FOR ALL TO authenticated USING (true) WITH CHECK (true);

